### ISSUE TITLE
It seems that we cannot create forks of this repository because it is empty. Perhaps you could add some content to this repository so we could create forks of it? It would be very nice even if you just `touch` an empty README.md, but I understand that given the outcome of e98e, that you might not want to do this. So, what do you say?

### ISSUE THREAD

**Issue by sigwinch28** [Ifyoudonotwantpeopleusingthemaximumchar/acterlimitthenyoushouldprobablylowerwhatthemaximumcharacterlimitis#2]

**Comment by ajford** [comment]
I second this.

**Comment by 0x0001F36D** [comment]
I just want to say Eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee

**Comment by NadyaNayme** [comment]
I've added a permissive license that allows it to become whatever anyone wants it to become for themselves. By doing so that should, to my understanding, allow the ability to fork this repository if you so wish.

In short, e.
