### ISSUE TITLE
Default branch name `master` is much too short.  I feel like it would be more in the spirit of the repository to rename it in such a way as to increase its length, without more clearly describing its purpose or function.  It may also be an interesting journey to discover what the maximum length of a branch name is in `git`.

### ISSUE THREAD

**Issue by Asday** [Ifyoudonotwantpeopleusingthemaximumchar/acterlimitthenyoushouldprobablylowerwhatthemaximumcharacterlimitis#8]

**Comment by altbdoor** [comment]
Perhaps `masteeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeer` ?

Someone on stackoverflow claims that GitHub's max is 255 characters.
https://stackoverflow.com/a/24014513

**Comment by NadyaNayme** [comment]
I tried 256 and decremented for a while before deciding to cut down to 128 characters. I have a feeling the limit is 128 but it could also be a random amount between 129 and 254 - possibly 140 as that's a seemingly common and arbitrary "rounding" of 128 that I come across frequently.

There is now a maste127e branch:
https://github.com/Ifyoudonotwantpeopleusingthemaximumchar/acterlimitthenyoushouldprobablylowerwhatthemaximumcharacterlimitis/tree/masteeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeer
